# coding: utf-8

"""
    Starburst Enterprise API documentation

    Documentation with details about endpoints and entities.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from sep_swagger_client.api_client import ApiClient


class LocationGrantsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_location_grant(self, role_id, **kwargs):  # noqa: E501
        """Add a LocationGrant to a role to allow accessing that location by the given role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_location_grant(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param CreateLocationGrantPayload body:
        :return: LocationGrantResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_location_grant_with_http_info(role_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_location_grant_with_http_info(role_id, **kwargs)  # noqa: E501
            return data

    def add_location_grant_with_http_info(self, role_id, **kwargs):  # noqa: E501
        """Add a LocationGrant to a role to allow accessing that location by the given role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_location_grant_with_http_info(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param CreateLocationGrantPayload body:
        :return: LocationGrantResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_location_grant" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `add_location_grant`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/locationGrants', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LocationGrantResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_location_grant(self, role_id, location_grant_id, **kwargs):  # noqa: E501
        """Remove a LocationGrant from a role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_location_grant(role_id, location_grant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int location_grant_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_location_grant_with_http_info(role_id, location_grant_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_location_grant_with_http_info(role_id, location_grant_id, **kwargs)  # noqa: E501
            return data

    def delete_location_grant_with_http_info(self, role_id, location_grant_id, **kwargs):  # noqa: E501
        """Remove a LocationGrant from a role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_location_grant_with_http_info(role_id, location_grant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int location_grant_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'location_grant_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_location_grant" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `delete_location_grant`")  # noqa: E501
        # verify the required parameter 'location_grant_id' is set
        if ('location_grant_id' not in params or
                params['location_grant_id'] is None):
            raise ValueError("Missing the required parameter `location_grant_id` when calling `delete_location_grant`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501
        if 'location_grant_id' in params:
            path_params['locationGrantId'] = params['location_grant_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/locationGrants/{locationGrantId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_location_grant(self, role_id, location_grant_id, **kwargs):  # noqa: E501
        """Get a Starburst built-in access control location grant of a role  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_location_grant(role_id, location_grant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int location_grant_id: (required)
        :return: LocationGrantResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_location_grant_with_http_info(role_id, location_grant_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_location_grant_with_http_info(role_id, location_grant_id, **kwargs)  # noqa: E501
            return data

    def get_location_grant_with_http_info(self, role_id, location_grant_id, **kwargs):  # noqa: E501
        """Get a Starburst built-in access control location grant of a role  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_location_grant_with_http_info(role_id, location_grant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int location_grant_id: (required)
        :return: LocationGrantResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'location_grant_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_location_grant" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `get_location_grant`")  # noqa: E501
        # verify the required parameter 'location_grant_id' is set
        if ('location_grant_id' not in params or
                params['location_grant_id'] is None):
            raise ValueError("Missing the required parameter `location_grant_id` when calling `get_location_grant`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501
        if 'location_grant_id' in params:
            path_params['locationGrantId'] = params['location_grant_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/locationGrants/{locationGrantId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LocationGrantResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_location_grants(self, role_id, **kwargs):  # noqa: E501
        """List Starburst built-in access control location grants of a role  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_location_grants(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param str page_token: Page token
        :param str page_size: Page size
        :param str page_sort: Sorting order
        :return: PaginatedResultLocationGrantResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_location_grants_with_http_info(role_id, **kwargs)  # noqa: E501
        else:
            (data) = self.list_location_grants_with_http_info(role_id, **kwargs)  # noqa: E501
            return data

    def list_location_grants_with_http_info(self, role_id, **kwargs):  # noqa: E501
        """List Starburst built-in access control location grants of a role  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_location_grants_with_http_info(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param str page_token: Page token
        :param str page_size: Page size
        :param str page_sort: Sorting order
        :return: PaginatedResultLocationGrantResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'page_token', 'page_size', 'page_sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_location_grants" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `list_location_grants`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501

        query_params = []
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_sort' in params:
            query_params.append(('pageSort', params['page_sort']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/locationGrants', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedResultLocationGrantResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
