# coding: utf-8

"""
    Starburst Enterprise API documentation

    Documentation with details about endpoints and entities.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from sep_swagger_client.api_client import ApiClient


class RowFiltersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_row_filter_to_role(self, role_id, **kwargs):  # noqa: E501
        """Add a row filter to a role to filter out table rows from queries made by subjects assigned to the role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_row_filter_to_role(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param RowFilterPayload body:
        :return: RowFilterResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_row_filter_to_role_with_http_info(role_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_row_filter_to_role_with_http_info(role_id, **kwargs)  # noqa: E501
            return data

    def add_row_filter_to_role_with_http_info(self, role_id, **kwargs):  # noqa: E501
        """Add a row filter to a role to filter out table rows from queries made by subjects assigned to the role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_row_filter_to_role_with_http_info(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param RowFilterPayload body:
        :return: RowFilterResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_row_filter_to_role" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `add_row_filter_to_role`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/rowFilters', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RowFilterResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_row_filter_expression(self, **kwargs):  # noqa: E501
        """Create an expression that can be applied to filter table rows from query results  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_row_filter_expression(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ExpressionPayload body:
        :return: ExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_row_filter_expression_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_row_filter_expression_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_row_filter_expression_with_http_info(self, **kwargs):  # noqa: E501
        """Create an expression that can be applied to filter table rows from query results  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_row_filter_expression_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ExpressionPayload body:
        :return: ExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_row_filter_expression" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/expressions/rowFilter', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExpressionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_role_row_filter(self, role_id, row_filter_id, **kwargs):  # noqa: E501
        """Remove a row filter from a role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_role_row_filter(role_id, row_filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int row_filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_role_row_filter_with_http_info(role_id, row_filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_role_row_filter_with_http_info(role_id, row_filter_id, **kwargs)  # noqa: E501
            return data

    def delete_role_row_filter_with_http_info(self, role_id, row_filter_id, **kwargs):  # noqa: E501
        """Remove a row filter from a role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_role_row_filter_with_http_info(role_id, row_filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int row_filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'row_filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_role_row_filter" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `delete_role_row_filter`")  # noqa: E501
        # verify the required parameter 'row_filter_id' is set
        if ('row_filter_id' not in params or
                params['row_filter_id'] is None):
            raise ValueError("Missing the required parameter `row_filter_id` when calling `delete_role_row_filter`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501
        if 'row_filter_id' in params:
            path_params['rowFilterId'] = params['row_filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/rowFilters/{rowFilterId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_row_filter_expression(self, row_filter_expression_id, **kwargs):  # noqa: E501
        """Delete a row filter expression  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_row_filter_expression(row_filter_expression_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int row_filter_expression_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_row_filter_expression_with_http_info(row_filter_expression_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_row_filter_expression_with_http_info(row_filter_expression_id, **kwargs)  # noqa: E501
            return data

    def delete_row_filter_expression_with_http_info(self, row_filter_expression_id, **kwargs):  # noqa: E501
        """Delete a row filter expression  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_row_filter_expression_with_http_info(row_filter_expression_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int row_filter_expression_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['row_filter_expression_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_row_filter_expression" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'row_filter_expression_id' is set
        if ('row_filter_expression_id' not in params or
                params['row_filter_expression_id'] is None):
            raise ValueError("Missing the required parameter `row_filter_expression_id` when calling `delete_row_filter_expression`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'row_filter_expression_id' in params:
            path_params['rowFilterExpressionId'] = params['row_filter_expression_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/expressions/rowFilter/{rowFilterExpressionId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_row_filter(self, role_id, row_filter_id, **kwargs):  # noqa: E501
        """Get a row filter of a given role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_row_filter(role_id, row_filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int row_filter_id: (required)
        :return: RowFilterResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_row_filter_with_http_info(role_id, row_filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_row_filter_with_http_info(role_id, row_filter_id, **kwargs)  # noqa: E501
            return data

    def get_row_filter_with_http_info(self, role_id, row_filter_id, **kwargs):  # noqa: E501
        """Get a row filter of a given role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_row_filter_with_http_info(role_id, row_filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param int row_filter_id: (required)
        :return: RowFilterResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'row_filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_row_filter" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `get_row_filter`")  # noqa: E501
        # verify the required parameter 'row_filter_id' is set
        if ('row_filter_id' not in params or
                params['row_filter_id'] is None):
            raise ValueError("Missing the required parameter `row_filter_id` when calling `get_row_filter`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501
        if 'row_filter_id' in params:
            path_params['rowFilterId'] = params['row_filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/rowFilters/{rowFilterId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RowFilterResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_row_filter_expression(self, row_filter_expression_id, **kwargs):  # noqa: E501
        """Get an expression that can be applied to filter table rows from query results  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_row_filter_expression(row_filter_expression_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int row_filter_expression_id: (required)
        :return: ExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_row_filter_expression_with_http_info(row_filter_expression_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_row_filter_expression_with_http_info(row_filter_expression_id, **kwargs)  # noqa: E501
            return data

    def get_row_filter_expression_with_http_info(self, row_filter_expression_id, **kwargs):  # noqa: E501
        """Get an expression that can be applied to filter table rows from query results  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_row_filter_expression_with_http_info(row_filter_expression_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int row_filter_expression_id: (required)
        :return: ExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['row_filter_expression_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_row_filter_expression" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'row_filter_expression_id' is set
        if ('row_filter_expression_id' not in params or
                params['row_filter_expression_id'] is None):
            raise ValueError("Missing the required parameter `row_filter_expression_id` when calling `get_row_filter_expression`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'row_filter_expression_id' in params:
            path_params['rowFilterExpressionId'] = params['row_filter_expression_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/expressions/rowFilter/{rowFilterExpressionId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExpressionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_role_row_filters(self, role_id, **kwargs):  # noqa: E501
        """List all the rows filters of a role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_role_row_filters(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param str page_token: Page token
        :param str page_size: Page size
        :param str page_sort: Sorting order
        :return: PaginatedResultRowFilterResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_role_row_filters_with_http_info(role_id, **kwargs)  # noqa: E501
        else:
            (data) = self.list_role_row_filters_with_http_info(role_id, **kwargs)  # noqa: E501
            return data

    def list_role_row_filters_with_http_info(self, role_id, **kwargs):  # noqa: E501
        """List all the rows filters of a role.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_role_row_filters_with_http_info(role_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int role_id: (required)
        :param str page_token: Page token
        :param str page_size: Page size
        :param str page_sort: Sorting order
        :return: PaginatedResultRowFilterResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['role_id', 'page_token', 'page_size', 'page_sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_role_row_filters" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'role_id' is set
        if ('role_id' not in params or
                params['role_id'] is None):
            raise ValueError("Missing the required parameter `role_id` when calling `list_role_row_filters`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'role_id' in params:
            path_params['roleId'] = params['role_id']  # noqa: E501

        query_params = []
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_sort' in params:
            query_params.append(('pageSort', params['page_sort']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/roles/{roleId}/rowFilters', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedResultRowFilterResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_row_filter_expressions(self, **kwargs):  # noqa: E501
        """List expressions that can be applied to filter table rows from query results  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_row_filter_expressions(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: PaginatedResultExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_row_filter_expressions_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.list_row_filter_expressions_with_http_info(**kwargs)  # noqa: E501
            return data

    def list_row_filter_expressions_with_http_info(self, **kwargs):  # noqa: E501
        """List expressions that can be applied to filter table rows from query results  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_row_filter_expressions_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: PaginatedResultExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_row_filter_expressions" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/expressions/rowFilter', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedResultExpressionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_row_filter_expression(self, row_filter_expression_id, **kwargs):  # noqa: E501
        """Update a row filter expression  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_row_filter_expression(row_filter_expression_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int row_filter_expression_id: (required)
        :param ExpressionPayload body:
        :return: ExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_row_filter_expression_with_http_info(row_filter_expression_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_row_filter_expression_with_http_info(row_filter_expression_id, **kwargs)  # noqa: E501
            return data

    def update_row_filter_expression_with_http_info(self, row_filter_expression_id, **kwargs):  # noqa: E501
        """Update a row filter expression  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_row_filter_expression_with_http_info(row_filter_expression_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int row_filter_expression_id: (required)
        :param ExpressionPayload body:
        :return: ExpressionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['row_filter_expression_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_row_filter_expression" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'row_filter_expression_id' is set
        if ('row_filter_expression_id' not in params or
                params['row_filter_expression_id'] is None):
            raise ValueError("Missing the required parameter `row_filter_expression_id` when calling `update_row_filter_expression`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'row_filter_expression_id' in params:
            path_params['rowFilterExpressionId'] = params['row_filter_expression_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/biac/expressions/rowFilter/{rowFilterExpressionId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExpressionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
