# coding: utf-8

"""
    Starburst Galaxy Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DiscoveredSqlStatement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sql': 'str',
        'status': 'str',
        'message': 'str'
    }

    attribute_map = {
        'sql': 'sql',
        'status': 'status',
        'message': 'message'
    }

    def __init__(self, sql=None, status=None, message=None):  # noqa: E501
        """DiscoveredSqlStatement - a model defined in Swagger"""  # noqa: E501
        self._sql = None
        self._status = None
        self._message = None
        self.discriminator = None
        self.sql = sql
        self.status = status
        if message is not None:
            self.message = message

    @property
    def sql(self):
        """Gets the sql of this DiscoveredSqlStatement.  # noqa: E501

        Raw generated SQL (read only)  # noqa: E501

        :return: The sql of this DiscoveredSqlStatement.  # noqa: E501
        :rtype: str
        """
        return self._sql

    @sql.setter
    def sql(self, sql):
        """Sets the sql of this DiscoveredSqlStatement.

        Raw generated SQL (read only)  # noqa: E501

        :param sql: The sql of this DiscoveredSqlStatement.  # noqa: E501
        :type: str
        """
        if sql is None:
            raise ValueError("Invalid value for `sql`, must not be `None`")  # noqa: E501

        self._sql = sql

    @property
    def status(self):
        """Gets the status of this DiscoveredSqlStatement.  # noqa: E501

        Status of the statement (read only)  # noqa: E501

        :return: The status of this DiscoveredSqlStatement.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DiscoveredSqlStatement.

        Status of the statement (read only)  # noqa: E501

        :param status: The status of this DiscoveredSqlStatement.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["Waiting", "Applying", "Success", "Errored", "Canceled"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def message(self):
        """Gets the message of this DiscoveredSqlStatement.  # noqa: E501

        Message describing statement or error message in case of execution failure (read only)  # noqa: E501

        :return: The message of this DiscoveredSqlStatement.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DiscoveredSqlStatement.

        Message describing statement or error message in case of execution failure (read only)  # noqa: E501

        :param message: The message of this DiscoveredSqlStatement.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiscoveredSqlStatement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiscoveredSqlStatement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
