# coding: utf-8

"""
    Starburst Galaxy Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Quotafailure(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_violations': 'list[FieldViolations]'
    }

    attribute_map = {
        'field_violations': 'fieldViolations'
    }

    def __init__(self, field_violations=None):  # noqa: E501
        """Quotafailure - a model defined in Swagger"""  # noqa: E501
        self._field_violations = None
        self.discriminator = None
        self.field_violations = field_violations

    @property
    def field_violations(self):
        """Gets the field_violations of this Quotafailure.  # noqa: E501


        :return: The field_violations of this Quotafailure.  # noqa: E501
        :rtype: list[FieldViolations]
        """
        return self._field_violations

    @field_violations.setter
    def field_violations(self, field_violations):
        """Sets the field_violations of this Quotafailure.


        :param field_violations: The field_violations of this Quotafailure.  # noqa: E501
        :type: list[FieldViolations]
        """
        if field_violations is None:
            raise ValueError("Invalid value for `field_violations`, must not be `None`")  # noqa: E501

        self._field_violations = field_violations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Quotafailure, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Quotafailure):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
