# coding: utf-8

"""
    Starburst Galaxy Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Scopes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_id': 'str',
        'entity_kind': 'str',
        'schema_name': 'str',
        'table_name': 'str',
        'column_name': 'str',
        'privileges': 'Privileges',
        'row_filter_ids': 'list[str]',
        'column_mask_id': 'str'
    }

    attribute_map = {
        'entity_id': 'entityId',
        'entity_kind': 'entityKind',
        'schema_name': 'schemaName',
        'table_name': 'tableName',
        'column_name': 'columnName',
        'privileges': 'privileges',
        'row_filter_ids': 'rowFilterIds',
        'column_mask_id': 'columnMaskId'
    }

    def __init__(self, entity_id=None, entity_kind=None, schema_name=None, table_name=None, column_name=None, privileges=None, row_filter_ids=None, column_mask_id=None):  # noqa: E501
        """Scopes - a model defined in Swagger"""  # noqa: E501
        self._entity_id = None
        self._entity_kind = None
        self._schema_name = None
        self._table_name = None
        self._column_name = None
        self._privileges = None
        self._row_filter_ids = None
        self._column_mask_id = None
        self.discriminator = None
        self.entity_id = entity_id
        self.entity_kind = entity_kind
        if schema_name is not None:
            self.schema_name = schema_name
        if table_name is not None:
            self.table_name = table_name
        if column_name is not None:
            self.column_name = column_name
        if privileges is not None:
            self.privileges = privileges
        self.row_filter_ids = row_filter_ids
        if column_mask_id is not None:
            self.column_mask_id = column_mask_id

    @property
    def entity_id(self):
        """Gets the entity_id of this Scopes.  # noqa: E501

        Entity ID  # noqa: E501

        :return: The entity_id of this Scopes.  # noqa: E501
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this Scopes.

        Entity ID  # noqa: E501

        :param entity_id: The entity_id of this Scopes.  # noqa: E501
        :type: str
        """
        if entity_id is None:
            raise ValueError("Invalid value for `entity_id`, must not be `None`")  # noqa: E501

        self._entity_id = entity_id

    @property
    def entity_kind(self):
        """Gets the entity_kind of this Scopes.  # noqa: E501

        Entity kind  # noqa: E501

        :return: The entity_kind of this Scopes.  # noqa: E501
        :rtype: str
        """
        return self._entity_kind

    @entity_kind.setter
    def entity_kind(self, entity_kind):
        """Sets the entity_kind of this Scopes.

        Entity kind  # noqa: E501

        :param entity_kind: The entity_kind of this Scopes.  # noqa: E501
        :type: str
        """
        if entity_kind is None:
            raise ValueError("Invalid value for `entity_kind`, must not be `None`")  # noqa: E501
        allowed_values = ["Account", "Cluster", "Catalog", "Schema", "Table", "Column", "Location", "Function", "Tag", "Policy", "RowFilter", "DataProduct"]  # noqa: E501
        if entity_kind not in allowed_values:
            raise ValueError(
                "Invalid value for `entity_kind` ({0}), must be one of {1}"  # noqa: E501
                .format(entity_kind, allowed_values)
            )

        self._entity_kind = entity_kind

    @property
    def schema_name(self):
        """Gets the schema_name of this Scopes.  # noqa: E501

        Schema name  # noqa: E501

        :return: The schema_name of this Scopes.  # noqa: E501
        :rtype: str
        """
        return self._schema_name

    @schema_name.setter
    def schema_name(self, schema_name):
        """Sets the schema_name of this Scopes.

        Schema name  # noqa: E501

        :param schema_name: The schema_name of this Scopes.  # noqa: E501
        :type: str
        """

        self._schema_name = schema_name

    @property
    def table_name(self):
        """Gets the table_name of this Scopes.  # noqa: E501

        Table name  # noqa: E501

        :return: The table_name of this Scopes.  # noqa: E501
        :rtype: str
        """
        return self._table_name

    @table_name.setter
    def table_name(self, table_name):
        """Sets the table_name of this Scopes.

        Table name  # noqa: E501

        :param table_name: The table_name of this Scopes.  # noqa: E501
        :type: str
        """

        self._table_name = table_name

    @property
    def column_name(self):
        """Gets the column_name of this Scopes.  # noqa: E501

        Column name  # noqa: E501

        :return: The column_name of this Scopes.  # noqa: E501
        :rtype: str
        """
        return self._column_name

    @column_name.setter
    def column_name(self, column_name):
        """Sets the column_name of this Scopes.

        Column name  # noqa: E501

        :param column_name: The column_name of this Scopes.  # noqa: E501
        :type: str
        """

        self._column_name = column_name

    @property
    def privileges(self):
        """Gets the privileges of this Scopes.  # noqa: E501


        :return: The privileges of this Scopes.  # noqa: E501
        :rtype: Privileges
        """
        return self._privileges

    @privileges.setter
    def privileges(self, privileges):
        """Sets the privileges of this Scopes.


        :param privileges: The privileges of this Scopes.  # noqa: E501
        :type: Privileges
        """

        self._privileges = privileges

    @property
    def row_filter_ids(self):
        """Gets the row_filter_ids of this Scopes.  # noqa: E501


        :return: The row_filter_ids of this Scopes.  # noqa: E501
        :rtype: list[str]
        """
        return self._row_filter_ids

    @row_filter_ids.setter
    def row_filter_ids(self, row_filter_ids):
        """Sets the row_filter_ids of this Scopes.


        :param row_filter_ids: The row_filter_ids of this Scopes.  # noqa: E501
        :type: list[str]
        """
        if row_filter_ids is None:
            raise ValueError("Invalid value for `row_filter_ids`, must not be `None`")  # noqa: E501

        self._row_filter_ids = row_filter_ids

    @property
    def column_mask_id(self):
        """Gets the column_mask_id of this Scopes.  # noqa: E501

        Column mask  # noqa: E501

        :return: The column_mask_id of this Scopes.  # noqa: E501
        :rtype: str
        """
        return self._column_mask_id

    @column_mask_id.setter
    def column_mask_id(self, column_mask_id):
        """Sets the column_mask_id of this Scopes.

        Column mask  # noqa: E501

        :param column_mask_id: The column_mask_id of this Scopes.  # noqa: E501
        :type: str
        """

        self._column_mask_id = column_mask_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Scopes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Scopes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
