# coding: utf-8

"""
    Starburst Galaxy Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateDataProductPatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'summary': 'str',
        'description': 'str',
        'contacts': 'list[ContactsPatch]',
        'default_cluster_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'summary': 'summary',
        'description': 'description',
        'contacts': 'contacts',
        'default_cluster_id': 'defaultClusterId'
    }

    def __init__(self, name=None, summary=None, description=None, contacts=None, default_cluster_id=None):  # noqa: E501
        """UpdateDataProductPatch - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._summary = None
        self._description = None
        self._contacts = None
        self._default_cluster_id = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if summary is not None:
            self.summary = summary
        if description is not None:
            self.description = description
        if contacts is not None:
            self.contacts = contacts
        if default_cluster_id is not None:
            self.default_cluster_id = default_cluster_id

    @property
    def name(self):
        """Gets the name of this UpdateDataProductPatch.  # noqa: E501

        Data Product name  # noqa: E501

        :return: The name of this UpdateDataProductPatch.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateDataProductPatch.

        Data Product name  # noqa: E501

        :param name: The name of this UpdateDataProductPatch.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def summary(self):
        """Gets the summary of this UpdateDataProductPatch.  # noqa: E501

        Short summary of Data Product  # noqa: E501

        :return: The summary of this UpdateDataProductPatch.  # noqa: E501
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this UpdateDataProductPatch.

        Short summary of Data Product  # noqa: E501

        :param summary: The summary of this UpdateDataProductPatch.  # noqa: E501
        :type: str
        """

        self._summary = summary

    @property
    def description(self):
        """Gets the description of this UpdateDataProductPatch.  # noqa: E501

        Long form description of Data Product  # noqa: E501

        :return: The description of this UpdateDataProductPatch.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateDataProductPatch.

        Long form description of Data Product  # noqa: E501

        :param description: The description of this UpdateDataProductPatch.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def contacts(self):
        """Gets the contacts of this UpdateDataProductPatch.  # noqa: E501


        :return: The contacts of this UpdateDataProductPatch.  # noqa: E501
        :rtype: list[ContactsPatch]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this UpdateDataProductPatch.


        :param contacts: The contacts of this UpdateDataProductPatch.  # noqa: E501
        :type: list[ContactsPatch]
        """

        self._contacts = contacts

    @property
    def default_cluster_id(self):
        """Gets the default_cluster_id of this UpdateDataProductPatch.  # noqa: E501

        Default cluster ID for Data Product  # noqa: E501

        :return: The default_cluster_id of this UpdateDataProductPatch.  # noqa: E501
        :rtype: str
        """
        return self._default_cluster_id

    @default_cluster_id.setter
    def default_cluster_id(self, default_cluster_id):
        """Sets the default_cluster_id of this UpdateDataProductPatch.

        Default cluster ID for Data Product  # noqa: E501

        :param default_cluster_id: The default_cluster_id of this UpdateDataProductPatch.  # noqa: E501
        :type: str
        """

        self._default_cluster_id = default_cluster_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateDataProductPatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateDataProductPatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
