# coding: utf-8

"""
    Starburst Galaxy Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateColumnMaskPatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'expression': 'str',
        'column_mask_type': 'str',
        'description': 'str'
    }

    attribute_map = {
        'name': 'name',
        'expression': 'expression',
        'column_mask_type': 'columnMaskType',
        'description': 'description'
    }

    def __init__(self, name=None, expression=None, column_mask_type=None, description=None):  # noqa: E501
        """UpdateColumnMaskPatch - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._expression = None
        self._column_mask_type = None
        self._description = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if expression is not None:
            self.expression = expression
        if column_mask_type is not None:
            self.column_mask_type = column_mask_type
        if description is not None:
            self.description = description

    @property
    def name(self):
        """Gets the name of this UpdateColumnMaskPatch.  # noqa: E501

        Column mask name  # noqa: E501

        :return: The name of this UpdateColumnMaskPatch.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateColumnMaskPatch.

        Column mask name  # noqa: E501

        :param name: The name of this UpdateColumnMaskPatch.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def expression(self):
        """Gets the expression of this UpdateColumnMaskPatch.  # noqa: E501

        Column mask expression  # noqa: E501

        :return: The expression of this UpdateColumnMaskPatch.  # noqa: E501
        :rtype: str
        """
        return self._expression

    @expression.setter
    def expression(self, expression):
        """Sets the expression of this UpdateColumnMaskPatch.

        Column mask expression  # noqa: E501

        :param expression: The expression of this UpdateColumnMaskPatch.  # noqa: E501
        :type: str
        """

        self._expression = expression

    @property
    def column_mask_type(self):
        """Gets the column_mask_type of this UpdateColumnMaskPatch.  # noqa: E501

        Column mask type  # noqa: E501

        :return: The column_mask_type of this UpdateColumnMaskPatch.  # noqa: E501
        :rtype: str
        """
        return self._column_mask_type

    @column_mask_type.setter
    def column_mask_type(self, column_mask_type):
        """Sets the column_mask_type of this UpdateColumnMaskPatch.

        Column mask type  # noqa: E501

        :param column_mask_type: The column_mask_type of this UpdateColumnMaskPatch.  # noqa: E501
        :type: str
        """
        allowed_values = ["Any", "Integer", "Boolean", "Date", "Decimal", "Real", "Double", "Timestamp", "TimestampWithTimeZone", "Time", "TimeWithTimeZone", "Varbinary", "Varchar"]  # noqa: E501
        if column_mask_type not in allowed_values:
            raise ValueError(
                "Invalid value for `column_mask_type` ({0}), must be one of {1}"  # noqa: E501
                .format(column_mask_type, allowed_values)
            )

        self._column_mask_type = column_mask_type

    @property
    def description(self):
        """Gets the description of this UpdateColumnMaskPatch.  # noqa: E501

        Description  # noqa: E501

        :return: The description of this UpdateColumnMaskPatch.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateColumnMaskPatch.

        Description  # noqa: E501

        :param description: The description of this UpdateColumnMaskPatch.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateColumnMaskPatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateColumnMaskPatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
