# coding: utf-8

"""
    Starburst Galaxy Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateUserPatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'update_role_grant': 'list[UpdateRoleGrantPatch]'
    }

    attribute_map = {
        'update_role_grant': 'updateRoleGrant'
    }

    def __init__(self, update_role_grant=None):  # noqa: E501
        """UpdateUserPatch - a model defined in Swagger"""  # noqa: E501
        self._update_role_grant = None
        self.discriminator = None
        if update_role_grant is not None:
            self.update_role_grant = update_role_grant

    @property
    def update_role_grant(self):
        """Gets the update_role_grant of this UpdateUserPatch.  # noqa: E501


        :return: The update_role_grant of this UpdateUserPatch.  # noqa: E501
        :rtype: list[UpdateRoleGrantPatch]
        """
        return self._update_role_grant

    @update_role_grant.setter
    def update_role_grant(self, update_role_grant):
        """Sets the update_role_grant of this UpdateUserPatch.


        :param update_role_grant: The update_role_grant of this UpdateUserPatch.  # noqa: E501
        :type: list[UpdateRoleGrantPatch]
        """

        self._update_role_grant = update_role_grant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateUserPatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateUserPatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
