# coding: utf-8

"""
    Starburst Enterprise API documentation

    Documentation with details about endpoints and entities.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CloneDataProductPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'new_name': 'str',
        'catalog_name': 'str',
        'data_domain_id': 'str'
    }

    attribute_map = {
        'new_name': 'newName',
        'catalog_name': 'catalogName',
        'data_domain_id': 'dataDomainId'
    }

    def __init__(self, new_name=None, catalog_name=None, data_domain_id=None):  # noqa: E501
        """CloneDataProductPayload - a model defined in Swagger"""  # noqa: E501
        self._new_name = None
        self._catalog_name = None
        self._data_domain_id = None
        self.discriminator = None
        self.new_name = new_name
        self.catalog_name = catalog_name
        if data_domain_id is not None:
            self.data_domain_id = data_domain_id

    @property
    def new_name(self):
        """Gets the new_name of this CloneDataProductPayload.  # noqa: E501

        Name for the new (cloned) data product.  # noqa: E501

        :return: The new_name of this CloneDataProductPayload.  # noqa: E501
        :rtype: str
        """
        return self._new_name

    @new_name.setter
    def new_name(self, new_name):
        """Sets the new_name of this CloneDataProductPayload.

        Name for the new (cloned) data product.  # noqa: E501

        :param new_name: The new_name of this CloneDataProductPayload.  # noqa: E501
        :type: str
        """
        if new_name is None:
            raise ValueError("Invalid value for `new_name`, must not be `None`")  # noqa: E501

        self._new_name = new_name

    @property
    def catalog_name(self):
        """Gets the catalog_name of this CloneDataProductPayload.  # noqa: E501

        Catalog for the cloned data product  # noqa: E501

        :return: The catalog_name of this CloneDataProductPayload.  # noqa: E501
        :rtype: str
        """
        return self._catalog_name

    @catalog_name.setter
    def catalog_name(self, catalog_name):
        """Sets the catalog_name of this CloneDataProductPayload.

        Catalog for the cloned data product  # noqa: E501

        :param catalog_name: The catalog_name of this CloneDataProductPayload.  # noqa: E501
        :type: str
        """
        if catalog_name is None:
            raise ValueError("Invalid value for `catalog_name`, must not be `None`")  # noqa: E501

        self._catalog_name = catalog_name

    @property
    def data_domain_id(self):
        """Gets the data_domain_id of this CloneDataProductPayload.  # noqa: E501

        Domain for the new data product.  If not specified then the domain of the source data product will be used.  # noqa: E501

        :return: The data_domain_id of this CloneDataProductPayload.  # noqa: E501
        :rtype: str
        """
        return self._data_domain_id

    @data_domain_id.setter
    def data_domain_id(self, data_domain_id):
        """Sets the data_domain_id of this CloneDataProductPayload.

        Domain for the new data product.  If not specified then the domain of the source data product will be used.  # noqa: E501

        :param data_domain_id: The data_domain_id of this CloneDataProductPayload.  # noqa: E501
        :type: str
        """

        self._data_domain_id = data_domain_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloneDataProductPayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloneDataProductPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
