# coding: utf-8

"""
    Starburst Enterprise API documentation

    Documentation with details about endpoints and entities.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConflictGrant(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'old_grant': 'GrantDto',
        'new_grant': 'GrantDto'
    }

    attribute_map = {
        'id': 'id',
        'old_grant': 'oldGrant',
        'new_grant': 'newGrant'
    }

    def __init__(self, id=None, old_grant=None, new_grant=None):  # noqa: E501
        """ConflictGrant - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._old_grant = None
        self._new_grant = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if old_grant is not None:
            self.old_grant = old_grant
        if new_grant is not None:
            self.new_grant = new_grant

    @property
    def id(self):
        """Gets the id of this ConflictGrant.  # noqa: E501


        :return: The id of this ConflictGrant.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConflictGrant.


        :param id: The id of this ConflictGrant.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def old_grant(self):
        """Gets the old_grant of this ConflictGrant.  # noqa: E501


        :return: The old_grant of this ConflictGrant.  # noqa: E501
        :rtype: GrantDto
        """
        return self._old_grant

    @old_grant.setter
    def old_grant(self, old_grant):
        """Sets the old_grant of this ConflictGrant.


        :param old_grant: The old_grant of this ConflictGrant.  # noqa: E501
        :type: GrantDto
        """

        self._old_grant = old_grant

    @property
    def new_grant(self):
        """Gets the new_grant of this ConflictGrant.  # noqa: E501


        :return: The new_grant of this ConflictGrant.  # noqa: E501
        :rtype: GrantDto
        """
        return self._new_grant

    @new_grant.setter
    def new_grant(self, new_grant):
        """Sets the new_grant of this ConflictGrant.


        :param new_grant: The new_grant of this ConflictGrant.  # noqa: E501
        :type: GrantDto
        """

        self._new_grant = new_grant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConflictGrant, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConflictGrant):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
