# coding: utf-8

"""
    Starburst Enterprise API documentation

    Documentation with details about endpoints and entities.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainReassignmentRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_product_ids': 'list[str]',
        'new_domain_id': 'str'
    }

    attribute_map = {
        'data_product_ids': 'dataProductIds',
        'new_domain_id': 'newDomainId'
    }

    def __init__(self, data_product_ids=None, new_domain_id=None):  # noqa: E501
        """DomainReassignmentRequest - a model defined in Swagger"""  # noqa: E501
        self._data_product_ids = None
        self._new_domain_id = None
        self.discriminator = None
        self.data_product_ids = data_product_ids
        self.new_domain_id = new_domain_id

    @property
    def data_product_ids(self):
        """Gets the data_product_ids of this DomainReassignmentRequest.  # noqa: E501

        List of Data Product IDs that will be reassigned  # noqa: E501

        :return: The data_product_ids of this DomainReassignmentRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._data_product_ids

    @data_product_ids.setter
    def data_product_ids(self, data_product_ids):
        """Sets the data_product_ids of this DomainReassignmentRequest.

        List of Data Product IDs that will be reassigned  # noqa: E501

        :param data_product_ids: The data_product_ids of this DomainReassignmentRequest.  # noqa: E501
        :type: list[str]
        """
        if data_product_ids is None:
            raise ValueError("Invalid value for `data_product_ids`, must not be `None`")  # noqa: E501

        self._data_product_ids = data_product_ids

    @property
    def new_domain_id(self):
        """Gets the new_domain_id of this DomainReassignmentRequest.  # noqa: E501

        All Data Products specified in the ID list will be reassigned to this domain.  # noqa: E501

        :return: The new_domain_id of this DomainReassignmentRequest.  # noqa: E501
        :rtype: str
        """
        return self._new_domain_id

    @new_domain_id.setter
    def new_domain_id(self, new_domain_id):
        """Sets the new_domain_id of this DomainReassignmentRequest.

        All Data Products specified in the ID list will be reassigned to this domain.  # noqa: E501

        :param new_domain_id: The new_domain_id of this DomainReassignmentRequest.  # noqa: E501
        :type: str
        """
        if new_domain_id is None:
            raise ValueError("Invalid value for `new_domain_id`, must not be `None`")  # noqa: E501

        self._new_domain_id = new_domain_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainReassignmentRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainReassignmentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
