# coding: utf-8

"""
    Starburst Enterprise API documentation

    Documentation with details about endpoints and entities.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from sep_swagger_client.models.subject_data import SubjectData  # noqa: F401,E501

class RoleSubjectData(SubjectData):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role_id': 'int'
    }
    if hasattr(SubjectData, "swagger_types"):
        swagger_types.update(SubjectData.swagger_types)

    attribute_map = {
        'role_id': 'roleId'
    }
    if hasattr(SubjectData, "attribute_map"):
        attribute_map.update(SubjectData.attribute_map)

    def __init__(self, role_id=None, *args, **kwargs):  # noqa: E501
        """RoleSubjectData - a model defined in Swagger"""  # noqa: E501
        self._role_id = None
        self.discriminator = None
        if role_id is not None:
            self.role_id = role_id
        SubjectData.__init__(self, *args, **kwargs)

    @property
    def role_id(self):
        """Gets the role_id of this RoleSubjectData.  # noqa: E501


        :return: The role_id of this RoleSubjectData.  # noqa: E501
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this RoleSubjectData.


        :param role_id: The role_id of this RoleSubjectData.  # noqa: E501
        :type: int
        """

        self._role_id = role_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoleSubjectData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleSubjectData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
